### ISSUE TITLE
Implement HikeFeedWebSocketServer

### ISSUE THREAD

**Issue by levani132** [SabaN24/HikingPartners#11]
HikeFeedWebSocketServer needs to implement four methods for getting new posts, comments or likes on them. This task will use some already created methods from database manager classes and will need some new methods in database manager.

First part - implement getting new post on the hike feed, putting it into database and returning back this new post to all connected sessions.
Second part - same things for new comments on post.
Third part - same thing for getting new likes of post.
Fourth part - same thing for new likes of comments.

**Comment by SabaN24** [comment]
Nodo24 implemented HikeFeedWebSocketServer
