### ISSUE TITLE
Implement HikeCommentsWebSocketServer

### ISSUE THREAD

**Issue by levani132** [SabaN24/HikingPartners#8]
HikeCommentsWebSocketServer getComment and getCommentLike request handlers needs to be implemented, should send information to DB and return back info about new comment or like to all connected sessions.

**Comment by levani132** [comment]
This task can be split into two parts, vache will do one implementing getting and returning comment.
Second part will be implementing getting and returning like to front.

**Comment by fkavache** [comment]
Done first half, ill push as soon as possible
